#!/usr/bin/env php
<?php
require(__DIR__ . "/inc/common.php");

try {
    psGet::init($argv);
    $args=PsGet::args($argv);
    if (count($args)<1) {
        PsOut::error("Error! Enter object[s] you want to get properities.\n".basename(__FILE__)
                . " resource \n"
                . "Available resources:\n"
                . psCli::helpResource()
                . "\n");
    }
    
    $object=array_shift($args);
    $objects=psCli::upobject($object);
    psGet::readcfg(Array("global","getvars",$objects));
    $webService = new PrestaShopWebservice(psCli::$shop_url, psCli::$shop_key, false);
    $opt = array('resource' => $objects);
    $xml = $webService->get($opt);
    $opt['id'] = (string) $xml->$objects->children()[0]["id"];
    $xml = $webService->get($opt);
    $rowobject = json_decode(json_encode($xml->children()->$object));
    $rowdata=psGet::getProperties($xml->children()->$object);
    psOut::write($rowdata);
    psOut::end($object);
} catch (PrestaShopWebserviceException $e) {
    // Here we are dealing with errors
    $trace = $e->getTrace();
    PsOut::error('Other error<br />' . $e->getMessage());
}


