#!/usr/bin/env php
<?php
require(__DIR__ . "/inc/common.php");
define("PSCMD","delete");

try {
    psGet::init($argv);
    $args=PsGet::$args;
    $object=array_shift($args);
    psGet::readcfg(Array("global","delete",$object));
    $args=PsGet::$args;
    array_shift($args);
    if (count($args)<1) {
        PsOut::error("Error! Enter object[s] you want to delete.\n".basename(__FILE__)
                . " resource id [property]...\n"
                . "Use --help to see available resources\n"
                . "\n");
    }
    $objects=psCli::upobject($object);
    $objectid = array_shift($args);
    $webService = new PrestaShopWebservice(psCli::$shop_url, psCli::$shop_key, false);
    $opt = array('resource' => $objects);
    $opt['id'] = $objectid;
    $xml = $webService->delete($opt);
} catch (PrestaShopWebserviceException $e) {
    // Here we are dealing with errors
    $trace = $e->getTrace();
    PsOut::error('Other error<br />' . $e->getMessage());
}


