#!/usr/bin/env php
<?php
require(__DIR__ . "/inc/common.php");
define("PSCMD","get");

try {
    psGet::init($argv);
    $args=PsGet::$args;
    $object=array_shift($args);
    psGet::readcfg(Array("global","get",$object));
    $args=PsGet::$args;
    array_shift($args);
    if (count($args)<1) {
        PsOut::error("Error! Enter object[s] you want to get.\n".basename(__FILE__)
                . " resource id [property]...\n"
                . "Property '*' or empty properties means everything.\n"
                . "Use --help to see available resources\n"
                . "\n");
    }
    $objects=psCli::upobject($object);
    $objectid = array_shift($args);
    $properties = array_flip($args);
    if (sizeof($properties)==0) {
        psCli::$properties=Array("*" => 1);
    }
    $webService = new PrestaShopWebservice(psCli::$shop_url, psCli::$shop_key, false);
    $opt = array('resource' => $objects);
    psOut::progress("Getting data for $objects($object)...");
    psOut::begin($object);
    $opt['id'] = $objectid;
    if (psCli::$debug) {
        psOut::msg("Options passed to api:\n");
        print_r($opt);
    }
    $Cache_Lite = new Cache_Lite(array(
        'cacheDir' => '/tmp/',
        'lifeTime' => 3600
    ));
    $id=md5(psCli::$shop_url.psCli::$shop_key.serialize($opt));
    if ($data = $Cache_Lite->get($id)) {
        $xml=New SimpleXMLElement($data);
    } else {
        $xml = $webService->get($opt);
        $Cache_Lite->save($xml->asXML(), $id);
    }
    $rowdata=psGet::getValues($xml->children()->$object);
    psOut::write($rowdata);
    psOut::end($object);
} catch (PrestaShopWebserviceException $e) {
    // Here we are dealing with errors
    $trace = $e->getTrace();
    PsOut::error('Other error<br />' . $e->getMessage());
}


