#!/usr/bin/env php
<?php
require(__DIR__ . "/inc/common.php");
define("PSCMD","list");

try {
    psCli::init($argv);
    $args = psCli::$args;
    $objects = array_shift($args);
    psCli::readcfg(Array("global","list",$objects));
    $args=psCli::$args;
    array_shift($args);
    if (strlen($objects)==0) {
        PsOut::error("Error! Enter objects you want to list.\n" . basename(__FILE__)
                . " resource [filter]... [id]...\n"
                . "Filter(s) can be either id of object or\n"
                . "property=value to match exactly\n"
                . "property>value to match objects with property bigger than value\n"
                . "property<value to match objects with property lower than value\n"
                . "property~value to match objects with property matched by regexp\n"
                . "property to match any value in property.\n"
                . "Use --help to get more informations\n\n"
                );
    }
    $object = psCli::subobject($objects);
    $properties = psCli::$properties;
    $ids=Array();
    $filter=Array();
    foreach ($args as $arg) {
        if (is_numeric($arg)) {
            $ids[$arg]=$arg;
        } else {
                $filter[] = $arg;
        }
    }
    if (sizeof($filter)>0) {
        psFilter::create($filter);
    }
    if (psCli::$debug) {
        psOut::msg("Filter: ".print_r($filter,true)."\n");
    }
    if (!psFilter::$enabled && count(psCli::$properties)>1) {
        psOut::error("You cannot get any properties without filter.");
    }
    $webService = new PrestaShopWebservice(psCli::$shop_url, psCli::$shop_key, false);
    $opt = array('resource' => $objects);
    psOut::progress("Getting data for $objects($object)...");
    $xml = $webService->get($opt);
    $data = $xml->$objects->children();
    $row = 0;
    $rows = Array();
    $cnt = sizeof($data);
    psOut::begin($objects, $object);
    foreach ($data as $r) {
        $rowdata = Array();
        $id = (string) $r["id"];
        if (sizeof($ids)>0 && !array_key_exists($id,$ids)) {
            continue;
        }
        if (psFilter::$enabled) {
            psOut::progress(false, $row, $cnt);
            $opt['id'] = $id;
            $xml = $webService->get($opt);
            $rowobject = json_decode(json_encode($xml->children()->$object));
            if (psFilter::$enabled && psFilter::isFiltered($rowobject)) {
                if (psCli::$debug)
                    psOut::msg("Filtering $object $id due to filter.\n");
                continue;
            }
            $rowdata = psGet::getValues($xml->children()->$object, psCli::$properties);
            psOut::write($rowdata);
        } else {
            psOut::write(Array("id" => (string) $id));
        }
        $row++;
    }
    psOut::end($objects, $object);
} catch (PrestaShopWebserviceException $e) {
    // Here we are dealing with errors
    $trace = $e->getTrace();
    PsOut::error('Other error<br />' . $e->getMessage());
}


