#!/usr/bin/env php
<?php
require(__DIR__ . "/inc/common.php");

psGet::init($argv);
foreach (psCli::$resources as $resource => $desc) {
    echo sprintf('%-30s %-30s %s'."\n", $resource, psCli::subobject($resource), $desc);
}


