#!/usr/bin/env php
<?php
require(__DIR__ . "/inc/common.php");

try {
    psGet::init($argv);
    $args=PsGet::$args;
    $object=array_shift($args);
    psGet::readcfg(Array("global","props",$object));
    $args=PsGet::$args;
    if (count($args)<1) {
        PsOut::error("Error! Enter object[s] you want to get properities.\n".basename(__FILE__)
                . " resource \n"
                . "Use --help to get more informations\n"
                . "\n");
    }
    $objects=psCli::upobject($object);
    $webService = new PrestaShopWebservice(psCli::$shop_url, psCli::$shop_key, false);
    $opt = array('resource' => $objects);
    $xml = $webService->get($opt);
    $opt['id'] = (string) $xml->$objects->children()[0]["id"];
    $xml = $webService->get($opt);
    $rowobject = json_decode(json_encode($xml->children()->$object));
    $rowdata=psGet::getProperties(psCli::filterProps($xml->children()->$object));
    foreach ($rowdata as $p) {
        echo  $p."\n";
    }
    psOut::end($object);
} catch (PrestaShopWebserviceException $e) {
    // Here we are dealing with errors
    $trace = $e->getTrace();
    PsOut::error('Other error<br />' . $e->getMessage());
}


