#!/usr/bin/env php
<?php
require(__DIR__ . "/inc/common.php");

try {
    psGet::init($argv);
    $args=PsGet::$args;
    $object=array_shift($args);
    psGet::readcfg(Array("global","update",$object));
    $args=PsGet::$args;
    array_shift($args);
    if (count($args)<2) {
        psOut::error("Error! Enter object[s] you want to update.\n".basename(__FILE__)
                . " resource id property=value [property=value]...\n"
                . "Use --help to get more informations\n"
                . "\n");
    }
    $objects=psCli::upobject($object);
    $objectid = array_shift($args);
    $update=psUpdate::create($args);
    if (!$update) {
        psOut::error("Bad update syntax? Run without parameters to get more help.");
    }
    $webService = new PrestaShopWebservice(psCli::$shop_url, psCli::$shop_key, false);
    $opt = array('resource' => $objects);
    psOut::progress("Getting data for $objects($object)...");
    $opt['id'] = $objectid;
    $xml = $webService->get($opt);
    $basefile=tempnam("/tmp","pscli");
    $origfile="$basefile.old";
    $newfile="$basefile.new";
    if (psCli::$debug || psCli::$dry) {
        $xml->asXML($origfile);
    }
    psUpdate::update($xml->children()->$object);
    $opt['putXml'] = $xml->asXML();
    if (psCli::$dry) {
        $xml->asXML($newfile);
        $d=popen("diff $origfile $newfile","r");
        fpassthru($d);
        psOut::msg("Dry mode. No modification made! See above if data are OK.\n");
    } else {
        $xml = $webService->edit($opt);
    }
    if (!psCli::$debug) {
        if (file_exists($origfile)) unlink($origfile);
        if (file_exists($newfile)) unlink($newfile);
    } else {
        psOut::msg("See $origfile and $newfile to compare changes.\n");
    }
} catch (PrestaShopWebserviceException $e) {
    // Here we are dealing with errors
    $trace = $e->getTrace();
    PsOut::error('Other error<br />' . $e->getMessage());
}


