#!/usr/bin/env php
<?php
require(__DIR__ . "/inc/common.php");

try {
    psGet::init($argv);
    $args=PsGet::args($argv);
    if (count($args)<3) {
        PsOut::error("Error! Enter object[s] you want to update.\n".basename(__FILE__)
                . " resource id property=value [property=value]...\n"
                . "Available resources:\n"
                . psCli::helpResource()
                . "\n");
    }
    
    $object=array_shift($args);
    $objects=psCli::upobject($object);
    psGet::readcfg(Array("global","update",$objects));
    $objectid = array_shift($args);
    $update=psUpdate::create($args);
    if (!$update) {
        psOut::error("Bad update syntax?");
    }
    $webService = new PrestaShopWebservice(psCli::$shop_url, psCli::$shop_key, false);
    $opt = array('resource' => $objects);
    psOut::progress("Getting data for $objects($object)...");
    $opt['id'] = $objectid;
    $xml = $webService->get($opt);
    $obj=$xml->children()->$object;
    $obj2=psUpdate::update($obj);
    $opt['putXml'] = $xml->asXML();
    $xml = $webService->edit($opt);
} catch (PrestaShopWebserviceException $e) {
    // Here we are dealing with errors
    $trace = $e->getTrace();
    PsOut::error('Other error<br />' . $e->getMessage());
}


